Modify pre-push

diff --git a/githooks/pre-push b/githooks/pre-push
--- a/githooks/pre-push
+++ b/githooks/pre-push
@@ -5,12 +5,19 @@ REMOTE_BRANCH=$(git ls-remote origin | grep -w $CURRENT_BRANCH)
 LAST_COMMIT=$(git rev-parse --short HEAD)
 LAST_COMMIT_GO_FILES=$(git diff-tree --no-commit-id --name-only -r $LAST_COMMIT | grep .go)
 
-if [ -z "$REMOTE_BRANCH" ]; then
-  [ -n "$LAST_COMMIT_GO_FILES" ] && { make test; exit 0; }
+RED=$(tput setaf 1)
+GREEN=$(tput setaf 2)
+
+# If there are no go files to push, then exit
+if [ -z "$LAST_COMMIT_GO_FILES" ]; then
+  exit 0
 fi
 
-DIFF_GO_FILES=$(git diff --name-only origin/$CURRENT_BRANCH | grep .go)
-
-[ -n "$DIFF_GO_FILES" ] && { make test; }
-
-exit 0;
+make test
+if [[ $? != 0 ]]; then
+  printf "${RED}Tests failed! ${NORMAL}Please fix tests before pushing.\n"
+  exit 1
+else
+ printf "${GREEN}Tests passed! ${NORMAL}Continuing to push.\n"
+ exit 0
+fi
